globals:
  baseline_program: P_none
  end_date:
  - 2026
  - 12
  - 31
  input_directory: ./inputs
  make_plots: true
  n_processes: null
  n_simulations: 2
  output_directory: ./outputs
  parameter_level: global
  pregenerate_leaks: true
  preseed_random: false
  print_from_simulations: true
  program_set_name: DEMO- Alt-LDAR Comparison - ZA
  reference_program: P_OGI
  start_date:
  - 2022
  - 1
  - 1
  version: '2.0'
  write_data: true
programs:
  P_Air:
    NRd: 365
    consider_weather: false
    economics:
      GWP_CH4: 28.0
      carbon_price_tonnesCO2e: 40.0
      cost_CCUS: 20.0
      repair_costs:
        file: null
        vals:
        - 200
      sale_price_natgas: 3.0
      verification_cost: 0
    emissions:
      LPR: 0.0065
      consider_venting: false
      leak_dist_params:
      - -1.79
      - 2.17
      leak_dist_type: lognorm
      leak_file: null
      leak_file_use: sample
      max_leak_rate: 100000
      subtype_leak_dist_file: null
      units:
      - kilogram
      - hour
      vent_file: site_rates.csv
    end_date:
    - 2026
    - 12
    - 31
    infrastructure_file: facilities_alberta-ex.csv
    method_labels:
    - M_Air
    - M_OGI_FollowUp
    methods:
      M_Air:
        RS: 4
        consider_daylight: true
        cost:
          per_day: 0
          per_hour: 0
          per_site: 100
          upfront: 0
        coverage:
          spatial: 1
          temporal: 1
        deployment_type: mobile
        follow_up:
          delay: 0
          instant_threshold: null
          instant_threshold_type: absolute
          interaction_priority: threshold
          min_followup_days_to_end: 0
          min_followup_type: annual
          min_followups: []
          preferred_method: null
          proportion: 1.0
          redundancy_filter: recent
          threshold: 0.0
          threshold_type: absolute
        is_follow_up: false
        label: M_Air
        max_workday: 8
        measurement_scale: site
        n_crews: 1
        parameter_level: method
        reporting_delay: 2
        scheduling:
          LDAR_crew_init_location:
          - -114.062
          - 51.044
          deployment_months:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          deployment_years: []
          home_bases_files: Airport_AB_Coordinates.csv
          route_planning: false
          travel_speeds: []
        sensor:
          MDL:
          - 0.791
          QE: 0.0
          mod_loc: null
          type: default
        t_bw_sites:
          file: null
          vals:
          - 5
        time: 1
        version: '2.0'
        weather_envs:
          precip:
          - 0.0
          - 0.5
          temp:
          - -40.0
          - 40.0
          wind:
          - 0.0
          - 10.0
      M_OGI_FollowUp:
        RS: null
        consider_daylight: true
        cost:
          per_day: 0
          per_hour: 0
          per_site: 600
          upfront: 0
        coverage:
          spatial: 1
          temporal: 1
        deployment_type: mobile
        follow_up:
          delay: 0
          instant_threshold: null
          instant_threshold_type: absolute
          interaction_priority: threshold
          min_followup_days_to_end: 0
          min_followup_type: annual
          min_followups: []
          preferred_method: null
          proportion: 1.0
          redundancy_filter: recent
          threshold: 0.0
          threshold_type: absolute
        is_follow_up: true
        label: M_OGI_FollowUp
        max_workday: 8
        measurement_scale: component
        n_crews: 1
        parameter_level: method
        reporting_delay: 2
        scheduling:
          LDAR_crew_init_location:
          - -114.062
          - 51.044
          deployment_months:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          deployment_years: []
          home_bases_files: Airport_AB_Coordinates.csv
          route_planning: false
          travel_speeds: []
        sensor:
          MDL:
          - 0.24
          - 0.39
          QE: 0.0
          mod_loc: null
          type: OGI_camera_zim
        t_bw_sites:
          file: null
          vals:
          - 30
        time: 80
        version: '2.0'
        weather_envs:
          precip:
          - 0.0
          - 0.5
          temp:
          - -40.0
          - 40.0
          wind:
          - 0.0
          - 10.0
    parameter_level: program
    program_name: P_Air
    repair_delay:
      type: default
      val:
      - 14.0
    site_samples: 100
    start_date:
    - 2022
    - 1
    - 1
    subtype_file: subtype_ex.csv
    subtype_times_file: null
    version: '2.0'
    weather_file: weather_alberta.nc
    weather_is_hourly: true
  P_Continuous:
    NRd: 365
    consider_weather: false
    economics:
      GWP_CH4: 28.0
      carbon_price_tonnesCO2e: 40.0
      cost_CCUS: 20.0
      repair_costs:
        file: null
        vals:
        - 200
      sale_price_natgas: 3.0
      verification_cost: 0
    emissions:
      LPR: 0.0065
      consider_venting: false
      leak_dist_params:
      - -1.79
      - 2.17
      leak_dist_type: lognorm
      leak_file: null
      leak_file_use: sample
      max_leak_rate: 100000
      subtype_leak_dist_file: null
      units:
      - kilogram
      - hour
      vent_file: site_rates.csv
    end_date:
    - 2026
    - 12
    - 31
    infrastructure_file: facilities_alberta-ex.csv
    method_labels:
    - M_Continuous
    - M_OGI_FollowUp
    methods:
      M_Continuous:
        RS: null
        consider_daylight: true
        cost:
          per_day: 5
          per_hour: 0
          per_site: 0
          upfront: 500
        coverage:
          spatial: 1
          temporal: 1
        deployment_type: stationary
        follow_up:
          delay: 0
          instant_threshold: null
          instant_threshold_type: absolute
          interaction_priority: threshold
          min_followup_days_to_end: 0
          min_followup_type: annual
          min_followups: []
          preferred_method: null
          proportion: 1.0
          redundancy_filter: recent
          threshold: 0.0
          threshold_type: absolute
        is_follow_up: false
        label: M_Continuous
        max_workday: 8
        measurement_scale: site
        n_crews: 1
        parameter_level: method
        reporting_delay: 2
        scheduling:
          LDAR_crew_init_location:
          - -114.062
          - 51.044
          deployment_months:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          deployment_years: []
          home_bases_files: Airport_AB_Coordinates.csv
          route_planning: false
          travel_speeds: []
        sensor:
          MDL:
          - 0.527
          QE: 0.0
          mod_loc: null
          type: default
        t_bw_sites:
          file: null
          vals:
          - 30.0
        time: null
        version: '2.0'
        weather_envs:
          precip:
          - 0.0
          - 0.5
          temp:
          - -40.0
          - 40.0
          wind:
          - 0.0
          - 10.0
      M_OGI_FollowUp:
        RS: null
        consider_daylight: true
        cost:
          per_day: 0
          per_hour: 0
          per_site: 600
          upfront: 0
        coverage:
          spatial: 1
          temporal: 1
        deployment_type: mobile
        follow_up:
          delay: 0
          instant_threshold: null
          instant_threshold_type: absolute
          interaction_priority: threshold
          min_followup_days_to_end: 0
          min_followup_type: annual
          min_followups: []
          preferred_method: null
          proportion: 1.0
          redundancy_filter: recent
          threshold: 0.0
          threshold_type: absolute
        is_follow_up: true
        label: M_OGI_FollowUp
        max_workday: 8
        measurement_scale: component
        n_crews: 1
        parameter_level: method
        reporting_delay: 2
        scheduling:
          LDAR_crew_init_location:
          - -114.062
          - 51.044
          deployment_months:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          deployment_years: []
          home_bases_files: Airport_AB_Coordinates.csv
          route_planning: false
          travel_speeds: []
        sensor:
          MDL:
          - 0.24
          - 0.39
          QE: 0.0
          mod_loc: null
          type: OGI_camera_zim
        t_bw_sites:
          file: null
          vals:
          - 30
        time: 80
        version: '2.0'
        weather_envs:
          precip:
          - 0.0
          - 0.5
          temp:
          - -40.0
          - 40.0
          wind:
          - 0.0
          - 10.0
    parameter_level: program
    program_name: P_Continuous
    repair_delay:
      type: default
      val:
      - 14.0
    site_samples: 100
    start_date:
    - 2022
    - 1
    - 1
    subtype_file: subtype_ex.csv
    subtype_times_file: null
    version: '2.0'
    weather_file: weather_alberta.nc
    weather_is_hourly: true
  P_OGI_1x:
    NRd: 365
    consider_weather: false
    economics:
      GWP_CH4: 28.0
      carbon_price_tonnesCO2e: 40.0
      cost_CCUS: 20.0
      repair_costs:
        file: null
        vals:
        - 200
      sale_price_natgas: 3.0
      verification_cost: 0
    emissions:
      LPR: 0.0065
      consider_venting: false
      leak_dist_params:
      - -1.79
      - 2.17
      leak_dist_type: lognorm
      leak_file: null
      leak_file_use: sample
      max_leak_rate: 100000
      subtype_leak_dist_file: null
      units:
      - kilogram
      - hour
      vent_file: site_rates.csv
    end_date:
    - 2026
    - 12
    - 31
    infrastructure_file: facilities_alberta-ex.csv
    method_labels:
    - M_OGI_1x
    methods:
      M_OGI_1x:
        RS: 1
        consider_daylight: true
        cost:
          per_day: 0
          per_hour: 0
          per_site: 600
          upfront: 0
        coverage:
          spatial: 1
          temporal: 1
        deployment_type: mobile
        follow_up:
          delay: 0
          instant_threshold: null
          instant_threshold_type: absolute
          interaction_priority: threshold
          min_followup_days_to_end: 0
          min_followup_type: annual
          min_followups: []
          preferred_method: null
          proportion: 1.0
          redundancy_filter: recent
          threshold: 0.0
          threshold_type: absolute
        is_follow_up: false
        label: M_OGI_1x
        max_workday: 8
        measurement_scale: component
        n_crews: 1
        parameter_level: method
        reporting_delay: 2
        scheduling:
          LDAR_crew_init_location:
          - -114.062
          - 51.044
          deployment_months:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          deployment_years: []
          home_bases_files: Airport_AB_Coordinates.csv
          route_planning: false
          travel_speeds: []
        sensor:
          MDL:
          - 0.24
          - 0.39
          QE: 0.0
          mod_loc: null
          type: OGI_camera_zim
        t_bw_sites:
          file: null
          vals:
          - 30
        time: 120
        version: '2.0'
        weather_envs:
          precip:
          - 0.0
          - 0.5
          temp:
          - -40.0
          - 40.0
          wind:
          - 0.0
          - 10.0
    parameter_level: program
    program_name: P_OGI_1x
    repair_delay:
      type: default
      val:
      - 14.0
    site_samples: 100
    start_date:
    - 2022
    - 1
    - 1
    subtype_file: subtype_ex.csv
    subtype_times_file: null
    version: '2.0'
    weather_file: weather_alberta.nc
    weather_is_hourly: true
  P_OGI_2x:
    NRd: 365
    consider_weather: false
    economics:
      GWP_CH4: 28.0
      carbon_price_tonnesCO2e: 40.0
      cost_CCUS: 20.0
      repair_costs:
        file: null
        vals:
        - 200
      sale_price_natgas: 3.0
      verification_cost: 0
    emissions:
      LPR: 0.0065
      consider_venting: false
      leak_dist_params:
      - -1.79
      - 2.17
      leak_dist_type: lognorm
      leak_file: null
      leak_file_use: sample
      max_leak_rate: 100000
      subtype_leak_dist_file: null
      units:
      - kilogram
      - hour
      vent_file: site_rates.csv
    end_date:
    - 2026
    - 12
    - 31
    infrastructure_file: facilities_alberta-ex.csv
    method_labels:
    - M_OGI_2x
    methods:
      M_OGI_2x:
        RS: 2
        consider_daylight: true
        cost:
          per_day: 0
          per_hour: 0
          per_site: 600
          upfront: 0
        coverage:
          spatial: 1
          temporal: 1
        deployment_type: mobile
        follow_up:
          delay: 0
          instant_threshold: null
          instant_threshold_type: absolute
          interaction_priority: threshold
          min_followup_days_to_end: 0
          min_followup_type: annual
          min_followups: []
          preferred_method: null
          proportion: 1.0
          redundancy_filter: recent
          threshold: 0.0
          threshold_type: absolute
        is_follow_up: false
        label: M_OGI_2x
        max_workday: 8
        measurement_scale: component
        n_crews: 1
        parameter_level: method
        reporting_delay: 2
        scheduling:
          LDAR_crew_init_location:
          - -114.062
          - 51.044
          deployment_months:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          deployment_years: []
          home_bases_files: Airport_AB_Coordinates.csv
          route_planning: false
          travel_speeds: []
        sensor:
          MDL:
          - 0.24
          - 0.39
          QE: 0.0
          mod_loc: null
          type: OGI_camera_zim
        t_bw_sites:
          file: null
          vals:
          - 30
        time: 120
        version: '2.0'
        weather_envs:
          precip:
          - 0.0
          - 0.5
          temp:
          - -40.0
          - 40.0
          wind:
          - 0.0
          - 10.0
    parameter_level: program
    program_name: P_OGI_2x
    repair_delay:
      type: default
      val:
      - 14.0
    site_samples: 100
    start_date:
    - 2022
    - 1
    - 1
    subtype_file: subtype_ex.csv
    subtype_times_file: null
    version: '2.0'
    weather_file: weather_alberta.nc
    weather_is_hourly: true
  P_OGI_4x:
    NRd: 365
    consider_weather: false
    economics:
      GWP_CH4: 28.0
      carbon_price_tonnesCO2e: 40.0
      cost_CCUS: 20.0
      repair_costs:
        file: null
        vals:
        - 200
      sale_price_natgas: 3.0
      verification_cost: 0
    emissions:
      LPR: 0.0065
      consider_venting: false
      leak_dist_params:
      - -1.79
      - 2.17
      leak_dist_type: lognorm
      leak_file: null
      leak_file_use: sample
      max_leak_rate: 100000
      subtype_leak_dist_file: null
      units:
      - kilogram
      - hour
      vent_file: site_rates.csv
    end_date:
    - 2026
    - 12
    - 31
    infrastructure_file: facilities_alberta-ex.csv
    method_labels:
    - M_OGI_4x
    methods:
      M_OGI_4x:
        RS: 4
        consider_daylight: true
        cost:
          per_day: 0
          per_hour: 0
          per_site: 600
          upfront: 0
        coverage:
          spatial: 1
          temporal: 1
        deployment_type: mobile
        follow_up:
          delay: 0
          instant_threshold: null
          instant_threshold_type: absolute
          interaction_priority: threshold
          min_followup_days_to_end: 0
          min_followup_type: annual
          min_followups: []
          preferred_method: null
          proportion: 1.0
          redundancy_filter: recent
          threshold: 0.0
          threshold_type: absolute
        is_follow_up: false
        label: M_OGI_4x
        max_workday: 8
        measurement_scale: component
        n_crews: 1
        parameter_level: method
        reporting_delay: 2
        scheduling:
          LDAR_crew_init_location:
          - -114.062
          - 51.044
          deployment_months:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          deployment_years: []
          home_bases_files: Airport_AB_Coordinates.csv
          route_planning: false
          travel_speeds: []
        sensor:
          MDL:
          - 0.24
          - 0.39
          QE: 0.0
          mod_loc: null
          type: OGI_camera_zim
        t_bw_sites:
          file: null
          vals:
          - 30
        time: 120
        version: '2.0'
        weather_envs:
          precip:
          - 0.0
          - 0.5
          temp:
          - -40.0
          - 40.0
          wind:
          - 0.0
          - 10.0
    parameter_level: program
    program_name: P_OGI_4x
    repair_delay:
      type: default
      val:
      - 14.0
    site_samples: 100
    start_date:
    - 2022
    - 1
    - 1
    subtype_file: subtype_ex.csv
    subtype_times_file: null
    version: '2.0'
    weather_file: weather_alberta.nc
    weather_is_hourly: true
  P_none:
    NRd: 365
    consider_weather: false
    economics:
      GWP_CH4: 28.0
      carbon_price_tonnesCO2e: 40.0
      cost_CCUS: 20.0
      repair_costs:
        file: null
        vals:
        - 200
      sale_price_natgas: 3.0
      verification_cost: 0
    emissions:
      LPR: 0.0065
      consider_venting: false
      leak_dist_params:
      - -1.79
      - 2.17
      leak_dist_type: lognorm
      leak_file: null
      leak_file_use: sample
      max_leak_rate: 100000
      subtype_leak_dist_file: null
      units:
      - kilogram
      - hour
      vent_file: site_rates.csv
    end_date:
    - 2026
    - 12
    - 31
    infrastructure_file: facilities_alberta-ex.csv
    method_labels: []
    methods: {}
    parameter_level: program
    program_name: P_none
    repair_delay:
      type: default
      val:
      - 14.0
    site_samples: 100
    start_date:
    - 2022
    - 1
    - 1
    subtype_file: subtype_ex.csv
    subtype_times_file: null
    version: '2.0'
    weather_file: weather_alberta.nc
    weather_is_hourly: true
subtype:
  LPR:
    0: 0.006
    1: 0.006
  NRd:
    0: 365
    1: 365
  dist_scale:
    0: -2
    1: -2
  dist_sigma:
    0: 1.4
    1: 1.2
  dist_type:
    0: lognorm
    1: lognorm
  subtype_code:
    0: compressor
    1: metering station
